name: Checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install linters
        run: pip install pycln isort black

      - name: Run Format Checks
        run: make check-format

  test:
    name: Test and Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry lock --check
          poetry install
      - name: Check pytorch version
        run: |
          poetry run python -Bc "import torch; print(torch.__version__)"
      - name: tests
        run: make test
      - name: upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage.txt
          path: coverage.txt
      - name: lint
        run: make lint
