name: Checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: pycln
        run: |
          pip install pycln
          pycln --check --config pyproject.toml .
      - name: isort
        run: |
          pip install isort
          isort --check-only .
      - name: black
        run: |
          pip install black
          python -m black --check .
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry lock --check
          poetry install
      - name: tests
        run: make test
